### ISSUE TITLE
Hardsetting Yii2 to 2.0.0 in composer fails to upgrade

### ISSUE THREAD

**Issue by gbcmd** [yiisoft/yii2-coding-standards#20]
Hardsetting 2.0.0 in the composer definition fails due to requirement of codesniffer 1.* where in the dev-master codesiffer * satisfies the dependency.

Should I be using 1.* if I am using 2.0.0 hardset?

**Comment by samdark** [comment]
I've just tagged 2.0.1 release where there's no restriction.

**Comment by gbcmd** [comment]
Thanks
