### ISSUE TITLE
Add Alphabetical sorting of use statements

### ISSUE THREAD

**Issue by antoniom** [yiisoft/yii2-coding-standards#25]
Something that I do a lot in my projects is having my use statements sorted lexicographically (Uppercase first, lowercase then).
Please have a look at some sniffs that already implement that feature [here](https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/Namespaces/AlphabeticallySortedUsesSniff.php) and [here](https://github.com/mayflower/mo4-coding-standard/blob/master/Sniffs/Formatting/AlphabeticalUseStatementsSniff.php).

**Comment by samdark** [comment]
I don't think that's something to force via coding standard.
