### ISSUE TITLE
Coding Standards Fixer for Yii 2

### ISSUE THREAD

**Issue by sergeymakinen** [yiisoft/yii2-coding-standards#31]
You're probably aware of [`php-cs-fixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer). Pretty useful and mature coding standards fixer.

It already includes lots of fixers (see the [rules list](https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage)) but Yii 2 has its specifics (especially PHPDocs)

### What I did

- I thought the Yii framework (and even 3rd party extensions whose want to stay up-to-date with the CS) can benefit from the work I have done (it's always cool when all code — yours and contributed — can be formatted in one command and you can even change some CS things fast and safely)
- I wrote several fixers and a config builder and tested everything on the Yii 2 framework code (I tried to follow the Yii 2 CS as much as I could)
- I'm ready to polish and tweak it to team's needs (and contribute/support it — although a code is not hard to understand)

### Possible usage

Let's assume we've pushed several files to `yii2-cs-fixer` — its `composer.json` is basically dependency-free (I wrote fixers for `php-cs-fixer` 2.0):

```json
"require-dev": {
    "friendsofphp/php-cs-fixer": "^2.0"
},
```

Then a project wishes to use our fixer will need:

- run `composer require --dev yiisoft/yii2-cs-fixer`
- place `.php_cs.dist` with this:

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

return yii2\csfixer\Config::create()
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in([
                // customizable
                __DIR__ . '/src',
                __DIR__ . '/tests',
                __DIR__ . '/yii2/framework',
            ])
            // customizable
            ->exclude('views')
    );
```
- run `php-cs-fixer fix` to fix it (or `php-cs-fixer fix --dry-run --diff` to preview changes)

### Summary

If you also think Yii 2 can benefit from this, I'm up to make it real — I will publish the source (it's not a prime-time ready yet — basically it misses docs) and tweak it to Yii 2 team needs.

In case you have questions or interested, I'm ready. If not, just close the issue. :)

There's a demo repository where I have applied fixes from my current configuration: https://github.com/sergeymakinen/yii2/commit/181e9e49d354a822d0add52062d4919bc2824b45

**Comment by cebe** [comment]
Thanks for offering this. However I disagree with most of the changes in the commit you showed, will comment on them later as I do not have the time for it right now.

**Comment by cebe** [comment]
Btw, there is already a fixer, which does some cleanup on docblocks: https://github.com/yiisoft/yii2/blob/master/build/controllers/PhpDocController.php#L72-L107

**Comment by sergeymakinen** [comment]
This fixer does a lot more on doc blocks.

> I disagree with most of the changes in the commit you showed

I can tweak a code style of course but the question is "could this fixer tool be useful for Yii 2?".
I mean I don't want to waste your time. But anyway, thanks for the feedback @cebe. :)

**Comment by cebe** [comment]
Of course it can be useful, it just needs some tweaks to fit our needs.

**Comment by sergeymakinen** [comment]
Since Robert is working on yiisoft/yii2#14100 and there’s nothing new since December, it’s time to close it.

**Comment by plumthedev** [comment]
Hello there!

Last time I was create new PHP-CS-Fixer config for Yii2 developers, I was grab ruleset from Yii2 ecosystem and my code is based on @rob006 original code.
Please take a look at your spare time.

Thanks, plumthedev!
