### ISSUE TITLE
Why use the Coding-sandards extension

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2-coding-standards#38]
hello, 
i came across your extension for the Yii coding standards and while going through the [Yii-coding standards Docs](https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md) i dont find anything that is not already covered by PhpCs, or maybe i am overlooking it.

The purpose of asking is that if i already am using the phpcs with PSR2 would i need to use this extension if i am working in Yii2 and how can it benefit me.

**Comment by machour** [comment]
Hi,

The docs reads: 

> The following code style is used for Yii 2.x core and official extensions development. If you want to pull-request code into the core, consider using it. 

This extension is meant to enforce some rules while developing Yii2, not with Yii2

> We aren't forcing you to use this code style for your application. Feel free to choose what suits you better.

You don't need this extension for your own projects.

**Comment by buttflattery** [comment]
That is what I thought initially, thanks a lot for your replies @machour @samdark .
