### ISSUE TITLE
404 on Manual & Guide link in Readme.MD

### ISSUE THREAD

**Issue by buttflattery** [yiisoft/yii2-coding-standards#39]
The link to the [`Manual & Guide`](http://pear.php.net/manual/en/package.php.php-codesniffer.php) link  under the **Usefull Links** needs to be updated it is throwing 404 Error, the link currently ponts to the url `http://pear.php.net/manual/en/package.php.php-codesniffer.php`

![image](https://user-images.githubusercontent.com/1536454/52128447-ce32f600-2656-11e9-8cb7-576006e0bab0.png)

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-coding-standards/commit/63385e68affa1295b0d29c5b8dafaa3fb450dd8c
