### ISSUE TITLE
PSR-12 standard release

### ISSUE THREAD

**Issue by razvanphp** [yiisoft/yii2-coding-standards#42]
Since Yii2 mostly follows the new extended rules, can we have a new release tag that enforces this standard?

It would help the community and junior developers follow the rules.

Thank you!
R

**Comment by samdark** [comment]
Could be done but needs work. Do you have some time for a pull request?

**Comment by razvanphp** [comment]
Sorry, you mean work for this repo only or to adjust also the framework code to pass all the new checks?

**Comment by samdark** [comment]
This repo only first.
