### ISSUE TITLE
Indentation fixing

### ISSUE THREAD

**Issue by maximal** [yiisoft/yii2-coding-standards#8]
PHP_CodeSniffer config treats this code as valid

```php
if (true) {
		// Note two tabs instead of one
		echo 'Hi there.', PHP_EOL;
}
```

Is there any way to fix this in CodeSniffer config?

**Comment by samdark** [comment]
It's not valid anymore since we've switched to spaces.

**Comment by maximal** [comment]
How does CodeSniffer treats 8 spaces here now?

**Comment by samdark** [comment]
Have no idea. Try it.
